### ISSUE TITLE
通过阿里云仓库是无法正常下载aar的,项目不打算维护了吗?

### ISSUE THREAD

**Issue by MicroKibaco** [mainlxl/Android-So-Handler#1]

**Comment by MicroKibaco** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by mainlxl** [comment]
并未上传至仓库 使用本地maven方式依赖  详见README

**Comment by MicroKibaco** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
